### ISSUE TITLE
avoid throw error if branch dose not exists

### ISSUE THREAD

**Issue by echoulen** [dawidd6/action-delete-branch#15]
if foo not exist the action will borken

```
- name: Delete foo branch
  uses: dawidd6/action-delete-branch@v3
  with:
    github_token: ${{github.token}}
    branches: foo
```
